variables:
    CYPRESS_SPEC: 'cypress/**/workflow/**/*.spec.js'
    PERCY_SPEC: 'cypress/**/visual/**/*.visual.spec.js'
    PLATFORM_BRANCH: "6.5.x"
    PERCY_TARGET_BRANCH: 'master'
    PLUGIN_DEPENDENCIES:
        value: >
            [
                { "name": "SwagCustomizedProducts", "url": "gitlab.shopware.com/shopware/6/services/customized-product", "branch": "6.5.x" },
                { "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "6.5.x" },
                { "name": "SwagAmazonPay", "url": "gitlab.shopware.com/shopware/6/services/swagamazonpay", "branch": "6.0-sw6.5.0.0" },
                { "name": "SwagCmsExtensions", "url": "gitlab.shopware.com/shopware/6/services/cms-extensions", "branch": "6.5.x" }
            ]
        description: 'Plugin dependencies. Defined in json. Example: [{ "name": "SwagPayPal", "url": "gitlab.shopware.com/shopware/6/services/paypal", "branch": "master" }]'
    COMPOSER_DEPENDENCIES:
        value: >
            [
              "theiconic/name-parser",
              "amzn/amazon-pay-api-sdk-php:2.5.2"
            ]
        description: 'Additional composer dependencies. Defined in json. Example: ["theiconic/name-parser", "amzn/amazon-pay-api-sdk-php:2.5.2"]'

include:
    project: 'shopware/6/product/platform'
    ref: '6.5.x'
    file: '.gitlab/templates/theme.yml'
